- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /

- platform: sql
  db_url: !secret db_link
  queries:
    - name: maria_db
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB

- platform: template
  sensors:
    home_is_empty:
      value_template: >
        {{ is_state("person.vladimir_friptu", "not_home") or is_state("person.natalia_friptu", "not_home") or is_state("person.iulia_anikeeva", "not_home")}}
